### ISSUE TITLE
Setting jdbc connection details in V44

### ISSUE THREAD

**Issue by rcronin** [damienchambe/metabase-db2-driver#3]
Has this driver been tested against V44? I just built this driver against tag v0.44.3 and running into an issue when validating JDBC connection details on the connection UI.

Here's the connection details: prompt=false;naming=sql;date format=iso;time format=hms;time separator=colon

I'm getting this error: [PWS0082] library(s) not added to the library list.

**Comment by damienchambe** [comment]
I upgraded my installation with  0.44.3 and it works the same as with 0.43
PW0082 is not a metabase error, but a JDBC error
see [https://www.ibm.com/mysupport/s/question/0D50z00006LKp7rCAD/pws0082-error-from-jdbc?language=fr](url)
Can you check the library you put in Metabase property  "Database name" exists ? It should be your main library
